repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: no-commit-to-branch
        args: ["--branch", "main"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
        exclude: (.vscode|.devcontainer)
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: "24.2.0"
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args:
          - --fix
