name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    name: Build and publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Build and publish
      uses: pypa/gh-action-pypi-publish@release/v1.8.11

  docs:
    name: Create documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4.1.5
    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install .[docs]
    - name: Build documentation
      run: |
        sphinx-build docs _build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/
        force_orphan: true
